
name: Robert Simoes
title: Robert Simoes
description: "Robert Simoes' blog about software - Ruby, Rails, Neovim, Architecture & More"
url: https://TODO.com
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme_options:
  google_analytics: G-241HN9TB7S

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
